### ISSUE TITLE
Integration with Appium ?

### ISSUE THREAD

**Issue by AdarshKumarGM** [ITArray/automotion-java#97]
I am wondering if this is possible to integrate with Appium. As on date, we don't have any tools to support CSS / Visual side of the apps using Javascript /Node JS. 

Is it possible to add this as an enhancement? or what do you suggest?

**Comment by dzaiats** [comment]
Hi @AdarshKumarGM , you can easily connect and use Autmotion with Appium project, doesn't matter if it is a native or hybrid app. Absolutely in the same way as it is presented on example for web project.

**Comment by AdarshKumarGM** [comment]
Okay, Thank you @dzaiats. I had a relook at the code being presented as examples. It mentions of using Java along with chrome/gecko drivers. 

Can you please add for Javascript/Node JS as well. Basically we need to install a node using NPM in Node JS and use it to import the underlying functions to be accessible for Automation in Appium.
