### ISSUE TITLE
Visual automation for iOS Native application using Appium - Reference boxes are not matching with the actual element

### ISSUE THREAD

**Issue by deeksha777** [ITArray/automotion-java#98]
Hi,

I am trying to work with visual automation with mobile applications(native), I am successfully able to do it in Android(native app), whereas in iOS, application is launching, but when checking whether an element isCenteredOnPageHorizontally/isLeftAlignedWith/isTopAlignedWith(using the same method name from framework), the test cases are failing, when checked the screenshots from the reports it is observed that even if the element is in the exact centre of the screen/either aligned in the left/top aligned the highlighted reference box(which is the part of framework in the report) is seen in the extreme left.

Note: Attached the report and the screenshots of the sample app(native app on iOS) for better understanding of the issue.
Issue Statement: **Hello World!!!** label is top aligned with **test** label, but the test is failing and also the reference box is shown at top left.
[reports.zip](https://github.com/ITArray/automotion-java/files/3016438/reports.zip)

Can you please help me resolve this issue, I guess some calculation is going wrong in taking the resolution of the screen.

**Comment by dzaiats** [comment]
Hi @deeksha777 , thank you for reporting this issue. Looks like that problem happens with the scale factor.
Could you please check which scale Factor do you use?
